name = "deathstar-phase1"
main = "src/index.ts"
compatibility_date = "2024-04-01"

[env.staging]
vars = { RPSLIMIT = "100", SOVEREIGN_KEY = "REPLACE_WITH_SECRET" }
d1_databases = [{ binding = "DB", database_name = "deathstarstaging", database_id = "REPLACE_WITH_ID" }]

[env.staging.ai]
binding = "AI"

[env.production]
vars = { RPSLIMIT = "1000", SOVEREIGN_KEY = "REPLACE_WITH_SECRET" }
d1_databases = [{ binding = "DB", database_name = "deathstarproduction", database_id = "REPLACE_WITH_ID" }]

[env.production.ai]
binding = "AI"
